// src/components/common/PageTransition.tsx
import React, { useEffect, useState } from 'react';
import { useLocation } from 'react-router-dom';

interface PageTransitionProps {
  children: React.ReactNode;
}

const PageTransition: React.FC<PageTransitionProps> = ({ children }) => {
  const location = useLocation();
  const [isTransitioning, setIsTransitioning] = useState(false);
  const [displayContent, setDisplayContent] = useState(children);

  useEffect(() => {
    setIsTransitioning(true);
    
    const transitionTimeout = setTimeout(() => {
      setDisplayContent(children);
      
      requestAnimationFrame(() => {
        setIsTransitioning(false);
      });
    }, 50);
    
    return () => clearTimeout(transitionTimeout);
  }, [location.pathname, children]);

  return (
    <div
      className={`transition-opacity duration-150 ${
        isTransitioning ? 'opacity-0' : 'opacity-100'
      }`}
    >
      {displayContent}
    </div>
  );
};

export default PageTransition;

// src/components/common/PageTransition.vue
<template>
  <div :class="`transition-opacity duration-150 ${isTransitioning ? 'opacity-0' : 'opacity-100'
    }`">
    <slot />
  </div>
</template>

<script setup lang="ts">
import { ref, watch, onUnmounted } from 'vue';
import { useRoute } from 'vue-router';

const route = useRoute();
const isTransitioning = ref(false);

let transitionTimeout: ReturnType<typeof setTimeout> | null = null;

watch(
  () => route.path,
  () => {
    isTransitioning.value = true;

    if (transitionTimeout) {
      clearTimeout(transitionTimeout);
    }

    transitionTimeout = setTimeout(() => {
      requestAnimationFrame(() => {
        isTransitioning.value = false;
      });
    }, 50);
  }
);

onUnmounted(() => {
  if (transitionTimeout) {
    clearTimeout(transitionTimeout);
  }
});
</script>
