// src/App.tsx
import { BrowserRouter as Router, Routes, Route, useLocation } from 'react-router-dom';
import { useEffect } from 'react';
import { ThemeProvider } from './context/ThemeContext';
import MainLayout from './layouts/MainLayout';
import RouteWrapper from './components/common/RouteWrapper';
import PageTransition from './components/common/PageTransition';
import routes from './routes/routes';

const GoogleAnalyticsTracker = () => {
  const location = useLocation();

  useEffect(() => {
    if (window.gtag) {
      window.gtag('config', import.meta.env.VITE_GA_MEASUREMENT_ID, {
        page_path: location.pathname,
      });
    }
  }, [location]);

  return null;
};

function App() {
  return (
    <ThemeProvider>
      <Router>
        <MainLayout>
          <GoogleAnalyticsTracker />
          <PageTransition>
            <Routes>
              {routes.map((route) => (
                <Route
                  key={route.path}
                  path={route.path}
                  element={<RouteWrapper {...route} />}
                />
              ))}
            </Routes>
          </PageTransition>
        </MainLayout>
      </Router>
    </ThemeProvider>
  );
}

export default App;

// src/App.vue
<template>
  <div id="app">
    <MainLayout>
      <PageTransition>
        <router-view />
      </PageTransition>
    </MainLayout>
  </div>
</template>

<script setup lang="ts">
import { watch } from 'vue';
import { useRoute } from 'vue-router';
import { useThemeProvider } from '@/composables/useTheme';
import MainLayout from '@/layouts/MainLayout.vue';
import PageTransition from '@/components/common/PageTransition.vue';

// Initialize theme provider
useThemeProvider();

// Google Analytics tracker
const route = useRoute();

watch(
  () => route.path,
  (path) => {
    if (window.gtag) {
      window.gtag('config', import.meta.env.VITE_GA_MEASUREMENT_ID, {
        page_path: path,
      });
    }
  },
  { immediate: true }
);
</script>
